# ~/.bashrc:executed by bash(1)for non-login shells.

# Note:PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
PS1='\h:\w\$ '
# umask 022
umask 000

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

# user defined alias
alias testd='cd ~/projects/test'
alias chmoda='chmod 777 -R ./'
alias prj='cd ~/projects'
CMDSTR1="dpkg -l | grep ^rc | awk ' { print \$2}' | xargs apt-get -y purge"
alias dpkgclr='echo "$CMDSTR1"' 
alias ifreset='ifrst() { ifdown $1; ifup $1; }; ifrst'

# sysver=`uname -v`
typeset -l sysver 
sysver=`cat /etc/issue`
if [[ $sysver =~ ubuntu ]]; then
    sys="ubuntu"
elif [[ $sysver =~ centos ]]; then
    sys="centos"
elif [[ $sysver =~ debian ]]; then
    sys="debian"
else 
    sys="unknown"
fi

if [[ $sys == "ubuntu" || $sys == "debian" ]]; then
    alias halt='shutdown now'
    alias aptupg='aptupg() { apt-spy -a Asia -d stable -t 5; apt-get update; apt-get -y   upgrade; }; aptupg; '
    alias appupg='appupg() { apt-get update; apt-get -y  upgrade; }; appupg; '
    alias appclr='appclr() { apt-get clean; apt-get -y autoremove; apt-get autoclean; apt-get -y purge; }; appclr; '
    alias install='apt-get install'
    #alias install='apt-get -y  install'
    alias remove='apt-get -y --purge remove'
    alias search='apt-cache search'
elif [[ $sys == "centos" ]]; then
    alias appupg='appupg() { yum update; yum -y  upgrade; }; appupg; '
    alias appclr='appclr() { yum clean; yum -y autoremove; yum autoclean; yum -y purge; }; appclr; '
    alias install='yum install'
    #alias install='yum -y  install'
    alias remove='yum -y remove'
    alias search='yum search'
fi
alias dsearch='dpkg -l | grep '

CMDSTR2="make mrprobe\r\nmake menuconfig\r\ncp /boot/config-??? .config\r\nmake -kpkg --initrd  --append-to-version=-liulang  -j 4 kernel_image kernel_headers"
alias kernel='echo -e "$CMDSTR2"'
alias makekernel='makekernel() { make menuconfig; make -kpkg clean; make -kpkg --initrd --append-to-version=-liulang --revision=1.0 kernel_image; }; makekernel; '
alias makeshare='mkdir -p $PRJROOT/share/ && rm -rf $PRJROOT/share/*.x $PRJROOT/share/*.ubi $PRJROOT/share/*.h && cp $PRJROOT/zebos/lib/mib_id.h $PRJROOT/share/ && cp $PRJROOT/zebos/lib/rpcl/*.x $PRJROOT/share/ -a && cp $PRJROOT/olt/rootfs_pack/rootfs.ubi $PRJROOT/share/ -a && rm -rf $PRJROOT/share/oltmib_erpsinfo.x && ls -l $PRJROOT/share/'

alias xindent='myindent() { file=$1; indent -o $file $file; }; myindent'
alias aindent='astyle --style=ansi -s4 -U -A10 --c --suffix=none -xe'
alias cindent='find . -name "*.[ch]" | grep -v .si4project | xargs clang-format -i'

tftpfile='/etc/default/tftpd-hpa'
tftpbasic='TFTP_USERNAME="root"\nTFTP_ADDRESS="0.0.0.0:69"\nTFTP_OPTIONS="-v -l -c -s"'
prjroot='/root/projects/'
olt=$prjroot"olt"
oltrel=$prjroot"olt/projects/prj_olt/release"
oltuboot=$prjroot"olt/olt/u-boot-2009.08"
xcat=$prjroot"xcat"
xcatrel=$prjroot"xcat/projects/prj_xcat/release"
xcatuboot=$prjroot"xcat/xcat/uboot_2010_12/build_output"
ac3=$prjroot"ac3"
ac3rel=$prjroot"ac3/projects/prj_sw_ac3/release"
ac3uboot=$prjroot"ac3/ac3/uboot_2010_12/build_output"
alias tftpshow='service tftpd-hpa status; cat $tftpfile'
alias tftpxcat='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$xcat >> $tftpfile && service tftpd-hpa restart'
alias tftpxcatuboot='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$xcatuboot >> $tftpfile && service tftpd-hpa restart'
alias tftpxcatrel='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$xcatrel >> $tftpfile && service tftpd-hpa restart'
alias tftpolt='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$olt >> $tftpfile && service tftpd-hpa restart'
alias tftpoltuboot='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$oltuboot >> $tftpfile && service tftpd-hpa restart'
alias tftpoltrel='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$oltrel >> $tftpfile && service tftpd-hpa restart'
alias tftpac3='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$ac3 >> $tftpfile && service tftpd-hpa restart'
alias tftpac3uboot='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$ac3uboot >> $tftpfile && service tftpd-hpa restart'
alias tftpac3rel='echo -e $tftpbasic > $tftpfile && echo TFTP_DIRECTORY=$ac3rel >> $tftpfile && service tftpd-hpa restart'

alias gen='ng generate'
alias serve='ng serve --host=0.0.0.0'

if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
if [[ $PWD == "/root" ]]; then
#    export PRJROOT=.
    cd $prjroot
fi
ulimit -c unlimited 

